ALTER TABLE students
  ADD COLUMN IF NOT EXISTS dob DATE DEFAULT NULL AFTER strand,
  ADD COLUMN IF NOT EXISTS gender VARCHAR(20) DEFAULT NULL AFTER dob,
  ADD COLUMN IF NOT EXISTS address TEXT DEFAULT NULL AFTER gender,
  ADD COLUMN IF NOT EXISTS phone VARCHAR(50) DEFAULT NULL AFTER address,
  ADD COLUMN IF NOT EXISTS email VARCHAR(100) DEFAULT NULL AFTER phone,
  ADD COLUMN IF NOT EXISTS parents TEXT DEFAULT NULL AFTER email;